// laboVue/src/components/Modules.vue
<template>
  <section class="container-fluid">

    <div v-for="module in modules" class="col-md-4">
      <article class="panel panel-primary">
        <div class="panel-heading">
          {{module.name}}
        </div>
        <div class="panel-body">
          {{module.description}}
          <div class="">
            <button type="button" class="btn btn-info" v-on:click="navigate(module)">Aller</button>
          </div>
        </div>
      </article>
    </div>

  </section>
</template>

<script>
import Modules from '@/properties/modules'

import Router from '@/router'

export default {
  name: 'modules',
  data () {
    return {
      modules: Modules
    }
  },
  methods: {
    navigate(module) {
      Router.push(module.path)
    }
  }
}
</script>

<style scoped>

</style>

// laboAngular/src/app/component/modules/modules.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { Module, Modules } from '../../properties/modules';

@Component({
  selector: 'app-modules',
  templateUrl: './modules.component.html',
  styleUrls: ['./modules.component.css']
})
export class ModulesComponent implements OnInit {

  modules;

  constructor(private router: Router) { }

  ngOnInit() {
    this.modules = Modules;
  }

  navigate(module: Module): void {
    this.router.navigate([module.path]);
  }

}

<section class="container-fluid">

  <div *ngFor="let module of modules" class="col-md-4">
    <article class="panel panel-primary">
      <div class="panel-heading">
        {{module.name}}
      </div>
      <div class="panel-body">
        {{module.description}}
        <div class="">
          <button type="button" class="btn btn-info" (click)="navigate(module)">Aller</button>
        </div>
      </div>
    </article>
  </div>

</section>
